---
#-------------------------------------#
# Pre-tasks run before anything else! #
#-------------------------------------#
- hosts: lxc
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: [ "always" ]
  gather_facts: false
  tasks:
    - import_tasks: tasks/pre-all.yml

#-----#
# LXC #
#-----#

- name: Setup and configure dev01 Container
  hosts: dev_lxc
  tags: [ "lxc-dev_lxc" ]
  become: true

  pre_tasks:  &pre_tasks

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

    - name: Apt Upgrade
      apt:
        name: '*'
        state: latest
        update_cache: true

  roles:
    - andrewrothstein.kubectl
    - gantsign.minikube
    - geerlingguy.helm    # Install helm on minikube nodes to deploy charts in ansible
    - geerlingguy.docker
    - geerlingguy.ntp
    - lxc/dev01

  tasks:

    - name: Copy git repos
      import_tasks: tasks/wsl/git.yml
      when: git
      tags: [ "git" ]

    - name: Setup aliases and functions in bash environment
      import_tasks: tasks/k3s/bashrc.yml

    - name: Setup dependencies
      import_tasks: tasks/k3s/dependencies.yml
      become: true

    # - name: deploy k8s manifests
    #   import_role:
    #     name: geerlingguy.k8s_manifests # Deploys everything inside file - `group_vars/k3s/vars.yml` lines - `43-46` variables - `k8s_*`
    #   tags: ['nfs', 'k8s_manifests']

    # - name: Deploy Helm Charts
    #   import_tasks: tasks/k3s/deploy_helm_charts.yml

- name: Setup Gitlab Runner LXC(s)
  hosts: gitlab_runner
  tags: [ "lxc-gitlab_runner" ]
  become: true

  pre_tasks:  *pre_tasks

  roles:

    - riemers.gitlab-runner
    - geerlingguy.docker
    - geerlingguy.ntp
    - lxc/gitlab-runner

### LDAP turnkey is a WIP

# - name: Setup and configure ldap Container
#   hosts: ldap
#   tags: [ "never", "lxc-ldap" ]
#   become: true

#   pre_tasks: *pre_tasks

#   roles:

#     - geerlingguy.ntp     # geerlingguy roles don't work in WSL.

#   tasks:

#     - name: Install OS updates and required packages
#       import_tasks: tasks/wsl/install_os_packages.yml
#       when: install_os_packages
#       tags: [ "install_os_packages" ]

#     - name: Copy git repos
#       import_tasks: tasks/wsl/git.yml
#       when: git
#       tags: [ "git" ]
