---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./jetstack.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./traefik.yml
