---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./file-browser-truenas.yaml
  - ./home-assistant.yaml
  - ./pfsense.yaml
  - ./proxmox.yml
  # - ./qbittorrent-nas.yml
  - ./synology-nas.yml
  # - ./transmission-nas.yml
  - ./truenas.yml
