---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginxhello
  namespace: default
spec:
  interval: 1m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginxhello
    namespace: default
  targetNamespace: default
