---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secrets/ks.yaml
  # - ./discord/alert.yml
  # - ./discord/provider.yml
  - ./namespace.yaml
  - ./reloader/ks.yaml
  # - ./snapshot-controller/ks.yaml
  # - ./volsync/ks.yaml
